### ISSUE TITLE
Store service, why filter out the recently added callback function from array?

### ISSUE THREAD

**Issue by shrestaz** [bulskov/RAWDATA_2019_Livecode11#1]
Hi Henrik,

Our group was not clear on this piece of code from the `store` service ([Livecode11/wwwroot/js/services/store.js - line 6 to 18](https://github.com/bulskov/RAWDATA_2019_Livecode11/blob/74c51a519d18f089795dbb6edd90bb53c60cf07b/Livecode11/wwwroot/js/services/store.js#L6-L18))

```js
var subscribers = []; // Initialize an array

var subscribe = function(callback) {
    subscribers.push(callback); // push the callback fn to the array
    return function() {
          subscribers = subscribers.filter(x => x !== callback); // filter out that callback from the array? 🤔
    };
};
```

1. Why do you filter out the callback function from the array which you added 2 lines above?
    - From our understanding of the MDN docs , [the filter() method creates a new array with all elements that pass the test implemented by the provided function.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter)
    - Shouldn't it be the other way round so we only have that recent callback function in the array? 
```js
subscribers = subscribers.filter(x => x === callback);
```

---- 

2. Why does the `subscribe` function return a function? (We can do the filter without the function and return void, no?)

\- Manish

**Comment by bulskov** [comment]
The return function from subscribe is the unsubscribe function. (so the callback is not filtered out before you execute the returned function.

var unsubscribe = subscribe(....);
.. do something ...
unsubscribe();
